### ISSUE TITLE
Anime titles? 

### ISSUE THREAD

**Issue by mathcass** [emleau/scifi_media#1]
I'm not sure if it's the most appropriate place for this, but here goes. 

I don't think I can go wrong by suggesting any of [Miyazaki's movies](http://www.imdb.com/name/nm0594503/?ref_=nv_sr_1) at all. They're all wonderful and great "scifi" films in their own ways. 

[Akira](http://www.imdb.com/title/tt0094625/?ref_=nv_sr_1) definitely falls into the "WTF" category while being a pretty compelling storyline.

Yet another WTF that falls under terrible but awesome is [Twilight of the Cockroaches](http://www.imdb.com/title/tt0093101/?ref_=fn_al_tt_1) which I've never found anywhere else except for the VHS of it off eBay.

**Comment by emleau** [comment]
I think these all definitely belong! Added 'em to the list. Thanks for the suggestions!
